React carousel component
vkahlon/c1121-code-solutions pull request #129
Opened 2022-02-08 19:14 UTC by vkahlon

Demo
![carousel](https://user-images.githubusercontent.com/47346471/153058532-776433fa-8107-4e5a-8a33-5c51a9fd752d.gif)

When I don't mess around

https://user-images.githubusercontent.com/47346471/153058826-c140b8d7-d07e-4656-badb-883f6cda865d.mp4

I forgot to show off the buttons...

https://user-images.githubusercontent.com/47346471/153058961-ce18486c-223b-4de6-b5bb-4d3d8db08770.mp4

2022-02-08 19:21 UTC, thebearingedge requested changes
Ok, great. Please define a method named `nextImage` that you can reuse, as there is a lot of duplication of the logic that goes to the next image.

2022-02-08 22:48 UTC, thebearingedge requested changes
Ok, getting better. Try moving this logic into nextImage()

```js
  const currentView = this.state.image;
  if (currentView === limit) {
    return this.setState({ image: 0 });
  } else {
    return this.setState({ image: this.state.image + 1 });
  }
```

Then do the interval setting/clearing in the click handlers and componentDidMount

```js
clearInterval(this.timer);
this.timer = setInterval(nextImage, 1000);
```

play around with the code organization such that you don't have duplication of the logic that chooses the "next" index to show.

2022-02-09 06:09 UTC, vkahlon commented
The Final Code doesn't have the two new images. Only in this demo
![demo 2](https://user-images.githubusercontent.com/47346471/153132090-18aad8b0-6a8a-4301-8c53-d50ef9fc0e6e.gif)

2022-02-10 15:47 UTC, thebearingedge approved these changes

2022-02-10 18:01 UTC, merged