Completed CSS-Brochure-Form.
vkahlon/c1121-code-solutions pull request #15
Opened 2021-12-02 06:57 UTC by vkahlon

![css-brochure-form](https://user-images.githubusercontent.com/47346471/144373149-ae355fb2-e77d-48fb-bff6-b95b09fe929d.png)

2021-12-02 07:03 UTC, vkahlon commented
![css-brochure-form](https://user-images.githubusercontent.com/47346471/144373802-fe7eaf70-f563-488b-91b6-bd1614394f6e.png)

2021-12-02 20:28 UTC, codingcodymiller requested changes
Hey Vick! just submitting a review so I know when you have updated this 🤓

2021-12-03 01:51 UTC, vkahlon commented
<img width="1103" alt="brochure resubmission" src="https://user-images.githubusercontent.com/47346471/144531006-a509d96b-1205-48aa-b89c-ea9ef6c8de20.png">
brochure resubmission

2021-12-03 01:52 UTC, codingcodymiller requested changes
Great work!! One minor note for you:

2021-12-03 01:52 UTC, codingcodymiller commented on css-brochure-form/styles.css
> +div {
I would do this on a class rather than the `div` element type. `div` elements are very common in HTML, you don't want to sweepingly change all their behavior like this.

2021-12-03 03:06 UTC, vkahlon commented on css-brochure-form/styles.css
> +div {
Made the necessary changes on the 4th commit. made a 5th recommit because my rgb value accidently got modified due to my laptop touchpad on the 4th. so on the 5th, its been restored!

2021-12-03 17:03 UTC, codingcodymiller approved these changes
Nice work!!

2021-12-03 17:27 UTC, merged