Css flexbox
vkahlon/c1121-code-solutions pull request #16
Opened 2021-12-02 19:11 UTC by vkahlon

![Screen Shot 2021-12-02 at 11 09 09 AM](https://user-images.githubusercontent.com/47346471/144487342-e1d0febd-6f8f-4dae-9e04-174a524c5f79.png)
![Screen Shot 2021-12-02 at 11 06 49 AM](https://user-images.githubusercontent.com/47346471/144487346-f0244bb5-58a9-4ab6-b227-e33456cffbc2.png)
![Screen Shot 2021-12-02 at 11 08 01 AM](https://user-images.githubusercontent.com/47346471/144487349-ca2e2864-5a78-4024-998a-b22e0b39fc4b.png)
![Screen Shot 2021-12-02 at 11 08 37 AM](https://user-images.githubusercontent.com/47346471/144487356-7cc80646-ed87-4c6f-a762-6762b0be797d.png)

2021-12-02 20:31 UTC, codingcodymiller requested changes
Hey Vick! You seem to have accidentally committed your Brochure Form code on this branch. I can help you get this cleaned up later on after you finish the current exercise 👍

2021-12-03 01:18 UTC, codingcodymiller requested changes

2021-12-03 01:18 UTC, codingcodymiller commented on css-flexbox/flex-wrap.html
> +        flex-basis: calc(100% / 6);
`flex-basis` is a property meant to be applied to the child elements of a flexbox, not the flexbox itself. This should be being applied to the `.card-wrapper` class

2021-12-03 01:18 UTC, codingcodymiller commented on css-flexbox/justify-content.html
> +        flex-basis: 25%;
`flex-basis` is a property meant to be applied to the child elements of a flexbox, not the flexbox itself. This should be being applied to the `.card-wrapper` class

2021-12-03 02:57 UTC, vkahlon commented on css-flexbox/justify-content.html
> +        flex-basis: 25%;
Made the necessary changes.

2021-12-03 16:56 UTC, codingcodymiller approved these changes

2021-12-03 17:27 UTC, merged