Completed Css canvas medical. Vick Kahlon
vkahlon/c1121-code-solutions pull request #26
Opened 2021-12-07 05:58 UTC by vkahlon

<img width="1366" alt="p1" src="https://user-images.githubusercontent.com/47346471/144974591-ece8b326-cae2-440c-be9c-df2166dca686.png">

<img width="1134" alt="p2" src="https://user-images.githubusercontent.com/47346471/144974379-cb692fdc-e81d-43ff-b7a7-8a49d271c69e.png">
<img width="1348" alt="p3" src="https://user-images.githubusercontent.com/47346471/144974393-090674bb-72e1-41c7-8b7e-580716d8953b.png">
>

2021-12-07 06:01 UTC, vkahlon commented
<img width="1440" alt="Screen Shot 2021-12-06 at 9 59 02 PM" src="https://user-images.githubusercontent.com/47346471/144974869-2b2447a0-7587-40f5-8949-28a3c4538e89.png">
<img width="1440" alt="Screen Shot 2021-12-06 at 9 59 15 PM" src="https://user-images.githubusercontent.com/47346471/144974906-fdbc2610-984d-49fa-b198-f53cc283c25a.png">

<img width="1440" alt="Screen Shot 2021-12-06 at 9 59 28 PM" src="https://user-images.githubusercontent.com/47346471/144974945-ec85c441-b1d3-481d-bc9d-e25c240bdd08.png">

re-Uploaded more consistent images.

2021-12-07 23:55 UTC, codingcodymiller requested changes
Hey Vick, nice start on this!! A few notes to get you started:

2021-12-07 23:55 UTC, codingcodymiller commented on css-canvas-medical/index.html
> +  </div>
Instead of creating a section of HTML just for the line, I would add a `border-bottom` to the `container` for the navbar.

2021-12-07 23:55 UTC, codingcodymiller commented on css-canvas-medical/styles.css
> +}
Instead of making a whole separate `container` class, I would make a class that just increases the width, and add that class in addition to the `container` class.

2021-12-07 23:55 UTC, codingcodymiller commented on css-canvas-medical/styles.css
> +.col-fourty {
This should be `.col-forty`

2021-12-07 23:55 UTC, codingcodymiller commented on css-canvas-medical/styles.css
> +.header-Links {
No capital letters in class names, classes should always be `kebab-case`, which includes no capital letters

2021-12-07 23:55 UTC, codingcodymiller commented on css-canvas-medical/styles.css
> +.heroMod {
`kebab-case`

2021-12-07 23:55 UTC, codingcodymiller commented on css-canvas-medical/styles.css
> +.buttonMod {
`kebab-case`

2021-12-07 23:55 UTC, codingcodymiller commented on css-canvas-medical/styles.css
> +h2.learnMore {
`kebab-case`

2021-12-07 23:55 UTC, codingcodymiller commented on css-canvas-medical/styles.css
> +p.scheduleMeeting {
`kebab-case`

2021-12-07 23:55 UTC, codingcodymiller commented on css-canvas-medical/styles.css
> +.whiteImage {
`kebab-case`

2021-12-08 05:15 UTC, vkahlon commented
<img width="1440" alt="Screen Shot 2021-12-07 at 9 10 39 PM" src="https://user-images.githubusercontent.com/47346471/145152190-5db93e65-66d6-4cbf-aca8-9fdf3ac4ae19.png">


<img width="1440" alt="Screen Shot 2021-12-07 at 9 10 54 PM" src="https://user-images.githubusercontent.com/47346471/145152096-eb5ce65e-a78f-4767-a706-4e39c32a466b.png">
>
<img width="1440" alt="Screen Shot 2021-12-07 at 9 11 04 PM" src="https://user-images.githubusercontent.com/47346471/145152143-de97b020-969c-4f93-924a-361e33887813.png">

2021-12-08 18:11 UTC, codingcodymiller requested changes

2021-12-13 18:23 UTC, codingcodymiller approved these changes
Great work!!

2021-12-13 18:24 UTC, merged