Completed javascript-functions. Vick Kahlon
vkahlon/c1121-code-solutions pull request #28
Opened 2021-12-07 23:48 UTC by vkahlon

<img width="1245" alt="functions" src="https://user-images.githubusercontent.com/47346471/145123265-72002c54-dd3e-4200-82ed-50b6af693cf1.png">

Heads up, I believe I did the objects section correctly, but due to function scope, it wont print with the rest of the output. therefore I did a bandaid solution with a console.log for the screenshot, however, at the bottom of the screenshot, you can see that I did the return function and it worked as intended.

2021-12-07 23:57 UTC, codingcodymiller requested changes

2021-12-07 23:57 UTC, codingcodymiller commented on javascript-functions/main.js
> +  return frenchName.firstName;
You can just `return person.firstName`

2021-12-07 23:57 UTC, codingcodymiller commented on javascript-functions/main.js
> +  console.log(seconds);
You shouldn't `console.log` the output inside the function, you should `return` the final output of the function, and you can log it where the function is called.

2021-12-07 23:57 UTC, codingcodymiller commented on javascript-functions/main.js
> +  console.log(greeting);
You shouldn't `console.log` the output inside the function, you should `return` the final output of the function, and you can log it where the function is called.

2021-12-07 23:57 UTC, codingcodymiller commented on javascript-functions/main.js
> +  console.log(area);
You shouldn't `console.log` the output inside the function, you should `return` the final output of the function, and you can log it where the function is called.

2021-12-08 00:09 UTC, vkahlon commented
Hopefully this fixes my beginner mistak
<img width="1251" alt="Screen Shot 2021-12-07 at 4 09 09 PM" src="https://user-images.githubusercontent.com/47346471/145125222-9c6de001-a4a4-4e0a-a787-00b7bb631da3.png">
e!

2021-12-08 17:19 UTC, codingcodymiller approved these changes

2021-12-08 17:20 UTC, merged