Css four column layout
vkahlon/c1121-code-solutions pull request #29
Opened 2021-12-08 01:28 UTC by vkahlon

<img width="1195" alt="four-column" src="https://user-images.githubusercontent.com/47346471/145132027-cb6352f3-5a27-43e6-9bf2-e93304046497.png">

2021-12-08 05:24 UTC, vkahlon commented
<img width="1194" alt="Screen Shot 2021-12-07 at 9 21 36 PM" src="https://user-images.githubusercontent.com/47346471/145153041-e3c6c2b7-06b9-4bf2-b4ba-302cbdd1df59.png">
 Fixed a typo and updated the screenshot.

2021-12-08 18:19 UTC, codingcodymiller requested changes

2021-12-08 18:19 UTC, codingcodymiller commented on css-four-column-layout/index.html
> +    </div>
I think your indentation got a bit messed up here, there are a couple of divs that seem to have a parent/child relationship, but they are at the same level of indentation 🤔

2021-12-08 23:02 UTC, vkahlon commented
fixed the indents

2021-12-09 20:45 UTC, codingcodymiller requested changes

2021-12-09 20:45 UTC, codingcodymiller commented on css-four-column-layout/index.html
> +        <div class = "row col-quarter">
No one element should be both a `row` and a `column` when using layout classes. You likely want this `column-fourth` to have a `row` class element as its child.

2021-12-09 20:45 UTC, codingcodymiller commented on css-four-column-layout/styles.css
> +  display: flex;
This looks like you should use the `row` class and just make a class to add the margin that you can use along with the `row` class.

2021-12-10 05:03 UTC, vkahlon commented
<img width="1085" alt="Screen Shot 2021-12-09 at 9 00 22 PM" src="https://user-images.githubusercontent.com/47346471/145520134-1a7c495f-758f-4923-ba0c-9a6f9b59c012.png">

2021-12-10 23:01 UTC, codingcodymiller approved these changes
Nice work!

2021-12-10 23:01 UTC, merged