Completed array-manipulation-1 exercise.
vkahlon/c1121-code-solutions pull request #37
Opened 2021-12-11 21:59 UTC by vkahlon

![cd194e7d1af91bc59ca398fffee08066](https://user-images.githubusercontent.com/47346471/145692882-6beca626-c1ce-42a6-982e-5233a91b4ba1.png)

2021-12-13 22:40 UTC, codingcodymiller requested changes

2021-12-13 22:40 UTC, codingcodymiller commented on array-manipulation-1/src/compact.js
> +   }
Whoops, you should fix up your indentation here 😬

2021-12-13 22:40 UTC, codingcodymiller commented on array-manipulation-1/src/initial.js
> +  } return newArray;
Please always keep the `return` expression on its own line, do not have it on the same line as a closing brace.

2021-12-13 22:40 UTC, codingcodymiller commented on array-manipulation-1/src/reverse.js
> +  {
What is the purpose of this code block?

2021-12-13 22:40 UTC, codingcodymiller commented on array-manipulation-1/src/tail.js
> +} return newArray;
Please fix your indentation and return statement placement

2021-12-13 23:00 UTC, vkahlon commented
Those were major formatting mistakes! Thanks for the support! eslint won't always be there to save us.

2021-12-14 00:48 UTC, codingcodymiller approved these changes

2021-12-14 01:03 UTC, merged