Completed object-manipulation-1 exercise.
vkahlon/c1121-code-solutions pull request #38
Opened 2021-12-12 01:09 UTC by vkahlon

![b13b25c4c0407cde7d1223509c0c2287](https://user-images.githubusercontent.com/47346471/145696729-e1232374-6e01-40f3-a0d5-8bc6d6d5ec3c.png)

2021-12-13 22:57 UTC, codingcodymiller requested changes

2021-12-13 22:57 UTC, codingcodymiller commented on object-manipulation-1/src/get-keys.js
> +  } return newArray;
`return` statement on its own line, please 🤓

2021-12-13 22:57 UTC, codingcodymiller commented on object-manipulation-1/src/get-values.js
> +  } return newArray;
`return` statement on its own line, please 🤓

2021-12-13 22:57 UTC, codingcodymiller commented on object-manipulation-1/src/to-object.js
> +} return newObject;
`return` statement on its own line, please 🤓

2021-12-13 22:57 UTC, codingcodymiller commented on object-manipulation-1/src/to-object.js
> +{
What is the purpose of this code block?

2021-12-14 01:39 UTC, vkahlon commented
<img width="1263" alt="Screen Shot 2021-12-13 at 5 35 25 PM" src="https://user-images.githubusercontent.com/47346471/145916899-1056b55d-229d-439a-9147-d70220d3247a.png">

For get-values, for whatever reason the eslint was messing up and saying GetValues function was never used, it would not allow me to commit it otherwise, so i had a make one. See screenshot

2021-12-14 19:06 UTC, codingcodymiller requested changes

2021-12-14 19:06 UTC, codingcodymiller commented on object-manipulation-1/src/get-values.js
> +getValues(object1);
It looks like you deleted the `/* exported getValues */` comment at the top of the file, if you re-add that, you can remove these lines 🤓

2021-12-15 04:37 UTC, vkahlon commented on object-manipulation-1/src/get-values.js
> +getValues(object1);
yea that makes sense. made the changes. what happened was that when i was doing this on my desktop, I did the wrong solution on the wrong js file, so i shifted around and copied and pasted. Since my eslint wasn't working at the time, it never detected it.

2021-12-15 19:03 UTC, codingcodymiller approved these changes

2021-12-15 21:19 UTC, merged