completed javascript-light-bulb challenge.
vkahlon/c1121-code-solutions pull request #44
Opened 2021-12-14 22:51 UTC by vkahlon

<img width="1178" alt="Screen Shot 2021-12-14 at 2 50 34 PM" src="https://user-images.githubusercontent.com/47346471/146091943-54de4d7e-59a6-4d70-b352-5df9374dfe37.png">

2021-12-14 23:03 UTC, codingcodymiller requested changes

2021-12-14 23:03 UTC, codingcodymiller commented on javascript-light-bulb/main.js
> +  if (clickCount % 2 === 1) {
In your code, you are using the count here only to determine if it is even or odd. There's another data type that is better to use for values that are one thing or the other thing: a boolean. You should instead make a boolean variable to keep track of if the light is currently on or not.

2021-12-15 00:01 UTC, vkahlon commented
I converted the primary if statement to boolean, I had to convert the number system into boolean system, but the benefit is that I can keep count of the clicks, if I have to.

2021-12-15 00:21 UTC, vkahlon commented
Do not grade this latest commit!

2021-12-15 00:25 UTC, vkahlon commented
Now it's ready to be graded.

2021-12-15 00:28 UTC, codingcodymiller approved these changes

2021-12-15 00:29 UTC, merged