Completed Javascript modal. Vick Kahlon
vkahlon/c1121-code-solutions pull request #46
Opened 2021-12-15 05:56 UTC by vkahlon

https://user-images.githubusercontent.com/47346471/146131404-270270bf-3b2b-4f93-a4f4-bbfbdd630b25.mp4

2021-12-15 19:31 UTC, codingcodymiller requested changes

2021-12-15 19:31 UTC, codingcodymiller commented on javascript-modal/mystyles.css
> +button.open-moda {
I think you meant to make this class `open-modal` 👀

2021-12-15 19:31 UTC, codingcodymiller commented on javascript-modal/mystyles.css
> +button.no-moda {
`no-modal` 👀

2021-12-15 21:27 UTC, vkahlon commented on javascript-modal/mystyles.css
> +button.no-moda {
the intention was worse, i always saw it as open moda! not open modal....

2021-12-16 20:34 UTC, codingcodymiller approved these changes

2021-12-16 20:35 UTC, merged