Object manipulation 3
vkahlon/c1121-code-solutions pull request #68
Opened 2022-01-13 01:09 UTC by vkahlon

Demo:

https://user-images.githubusercontent.com/47346471/149247834-234cd308-da2e-432f-b0c3-1bf97b6c4465.mp4

2022-01-13 18:43 UTC, codingcodymiller requested changes

2022-01-13 18:43 UTC, codingcodymiller commented on object-manipulation-3/main.js
> +var hand4 = [shuffledCards[6], shuffledCards[7]];
When you deal a card to a player, it should be removed from the deck, just like real cards.

2022-01-13 18:43 UTC, codingcodymiller commented on object-manipulation-3/main.js
> +console.log('Fourth place is ' + grabWinnerList[0].name + ' who had ' + grabWinnerList[0].points + ' points.');
What if there's a tie? :thinking:

2022-01-13 22:06 UTC, vkahlon commented
<img width="716" alt="tie" src="https://user-images.githubusercontent.com/47346471/149416569-b5ef709c-04e4-4b30-89eb-8991bc546034.png">

2022-01-13 23:10 UTC, codingcodymiller requested changes

2022-01-13 23:10 UTC, codingcodymiller commented on object-manipulation-3/main.js
> +    console.log('The runner-up is ' + startNewRound[0].name + ' who had ' + startNewRound[0].points + ' points.');
What if **_this_** game has a tie? 🤔

2022-01-14 01:18 UTC, vkahlon commented
<img width="724" alt="Screen Shot 2022-01-13 at 5 16 48 PM" src="https://user-images.githubusercontent.com/47346471/149434589-46853753-ca89-4c41-a335-f0ebeb0b8045.png">

2022-01-19 20:47 UTC, thebearingedge requested changes

2022-01-19 20:47 UTC, thebearingedge commented on object-manipulation-3/main.js
> +    return list;
If you use two nested loops you can create every card the same way inside of the inner loop.

```js
var ranks = ['ace', 'king', 'queen', 'jack', 10, 9, 8, 7, 5, 4, 3, 2];
var suits = ['hearts', 'clubs', 'diamonds', 'spades'];
```

2022-01-21 18:11 UTC, thebearingedge approved these changes

2022-01-24 17:53 UTC, merged