Completed html-forms exercise. Vick Kahlon
vkahlon/c1121-code-solutions pull request #7
Opened 2021-11-30 23:07 UTC by vkahlon

<img width="1118" alt="html-form" src="https://user-images.githubusercontent.com/47346471/144142515-103ad479-f8ea-48d3-9d88-3c45911b6c1d.png">

address bar contains info

2021-11-30 23:13 UTC, vkahlon commented
2nd submission was to make it less confusing for the input type email section

2021-12-01 00:45 UTC, codingcodymiller requested changes

2021-12-01 00:45 UTC, codingcodymiller commented on html-forms/index.html
> +        <input type="radio" name="language" value="HTML" />HTML
This text labeling the `input` should be in a `label` element.

2021-12-01 00:45 UTC, codingcodymiller commented on html-forms/index.html
> +        <input type="radio" name="language" value="CSS" />CSS
This text labeling the `input` should be in a `label` element.

2021-12-01 00:45 UTC, codingcodymiller commented on html-forms/index.html
> +        <input type="radio" name="language" value="JavaScript" />JavaScript
This text labeling the `input` should be in a `label` element.

2021-12-01 17:46 UTC, codingcodymiller approved these changes

2021-12-01 17:50 UTC, merged