Completed express-delete exercise.
vkahlon/c1121-code-solutions pull request #91
Opened 2022-01-25 23:37 UTC by vkahlon

![2](https://user-images.githubusercontent.com/47346471/151077805-2eedb3ea-6007-48ae-80ba-5baa8fb1e204.png)
![1](https://user-images.githubusercontent.com/47346471/151077808-f2fc860e-cea6-409e-a391-38b946c27d62.png)

2022-01-25 23:55 UTC, thebearingedge requested changes

2022-01-25 23:55 UTC, thebearingedge commented on express-delete/index.js
> +});
The client should receive an array of objects here

2022-01-26 00:01 UTC, vkahlon commented
<img width="376" alt="fix" src="https://user-images.githubusercontent.com/47346471/151080035-d1007333-d80c-4773-90b3-d21378d0e4e9.png">

2022-01-26 00:13 UTC, thebearingedge approved these changes

2022-01-26 00:15 UTC, merged